Repository mpawank/Rohit-Youtube-Advocate-AiBot, pull requests merged in 2025-10, with the labels that each got.

#86 Professional Invoice Creator Component Enhancement
  frontend/src/components/InvoiceGenerator.jsx
Labels: gssoc25, level3

#88 Landing Page Hero Component Enhancement
  frontend/src/components/LandingPage.jsx
Labels: enhancement, gssoc25, level3

#74 RAG Pipeline Code Refactor and Documentation Enhancementy
  backend/rag_pipeline.py
Labels: enhancement, gssoc25, level2

#84 Hero Section Styling Enhancement
  frontend/src/components/HeroSection.css
Labels: gssoc25, level1

#76 Backend Service Code Refactor and Documentation Enhancement
  backend/vector_database.py
Labels: enhancement, gssoc25, level3

#78 YouTube Advisor Component Enhancementdate AMA.jsx
  frontend/src/components/AMA.jsx
Labels: enhancement, gssoc25, level3

#99 feat: Mobile navigation overhaul and code structure refactor 📱
  frontend/src/App.jsx
Labels: enhancement, gssoc25, level3

#95 🔧 DX: Add Development Tooling Improvements and Dependency Audit Comments
  frontend/package-lock.json
Labels: enhancement, gssoc25, level3

#97 🎨 ENHANCEMENT: Improve HTML Structure with Semantic Comments and Accessibility
  frontend/index.html
Labels: gssoc25, level3

#101 🎨 ENHANCEMENT: Improve CSS Structure with Semantic Comments and Responsive Design
  frontend/src/styles/LandingPage.css
Labels: enhancement, gssoc25, level3

#111 ✨ ENHANCEMENT: Enhance Flask API Structure & Developer Experience
  backend/app.py
Labels: enhancement, gssoc25, level2

#109 added dark mode toggle
  frontend/package-lock.json
  frontend/src/components/HeroSection.css
  frontend/src/styles/theme.css
Labels: gssoc25, level3
